=== Lesotho-eLMIS/lesotho-fulfillment/src/main/resources/schemas/orderLineItem.json
{ "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "OrderLineItem",
  "description": "A single orderLineItem",
  "properties": {
    "id": {
      "type": "string",
      "required": true,
      "title": "id"
    },
    "orderableProductId": {
      "type": "string",
      "required": true,
      "title": "orderableProductId"
    },
    "orderedQuantity": {
      "type": "integer",
      "required": true,
      "title": "orderedQuantity"
    },
    "order": {
      "type": "object",
      "$ref": "order.json",
      "required": false,
      "title": "order"
    },
    "filledQuantity": {
      "type": "integer",
      "required": true,
      "title": "filledQuantity"
    }
  }
}

=== Lesotho-eLMIS/lesotho-fulfillment/demo-data/olmis_order.order_line_items.json
[
  {
    "id": "9a4c65f9-f834-44bb-9e75-2c18c9a2a9cf",
    "order": { "id": "35e5059a-fd92-4078-a448-b00402b3fb5b" },
    "orderableProductId": "2400e410-b8dd-4954-b1c0-80d8a8e785fc",
    "orderedQuantity": 50,
    "filledQuantity": 100
  },
  {
    "id": "7b1b735d-c29a-4486-8352-04d3034e0d77",
    "order": { "id": "35e5059a-fd92-4078-a448-b00402b3fb5b" },
    "orderableProductId": "103396e1-f5e4-4754-bb7b-1c799097dfea",
    "orderedQuantity": 0,
    "filledQuantity": 50
  },
  {
    "id": "5a38bb94-b206-4575-9555-883d4eecc5cc",
    "order": { "id": "5edbb162-721d-4abb-adbf-09ab6130d8e6" },
    "orderableProductId": "2400e410-b8dd-4954-b1c0-80d8a8e785fc",
    "orderedQuantity": 0,
    "filledQuantity": 800
  },
  {
    "id": "657686c4-dbf7-4c1d-b491-1f650002fa39",
    "order": { "id": "5edbb162-721d-4abb-adbf-09ab6130d8e6" },
    "orderableProductId": "c9e65f02-f84f-4ba2-85f7-e2cb6f0989af",
    "orderedQuantity": 0,
    "filledQuantity": 250
  },
  {
    "id": "c57e407a-7bad-4e52-aee4-6f1742468d61",
    "order": { "id": "90ddacf9-2280-4e8c-80f7-4e2e0251f8f3" },
    "orderableProductId": "2400e410-b8dd-4954-b1c0-80d8a8e785fc",
    "orderedQuantity": 50,
    "filledQuantity": 50
  },
  {
    "id": "0e30fa6e-dca8-4b43-aa78-bf5fc3a09ef3",
    "order": { "id": "90ddacf9-2280-4e8c-80f7-4e2e0251f8f3" },
    "orderableProductId": "103396e1-f5e4-4754-bb7b-1c799097dfea",
    "orderedQuantity": 0,
    "filledQuantity": 70
  },
  {
    "id": "241e50a9-14c3-4b04-b161-915aa20d49da",
    "order": { "id": "ec49baf1-fb6c-4bbc-ad5e-54fff70115a2" },
    "orderableProductId": "2400e410-b8dd-4954-b1c0-80d8a8e785fc",
    "orderedQuantity": 0,
    "filledQuantity": 30
  },
  {
    "id": "739a2eb5-705a-4d0a-a7e9-a01146e1441b",
    "order": { "id": "ec49baf1-fb6c-4bbc-ad5e-54fff70115a2" },
    "orderableProductId": "c9e65f02-f84f-4ba2-85f7-e2cb6f0989af",
    "orderedQuantity": 0,
    "filledQuantity": 1200
  }
]
